### PR TITLE
Adds proper ESM and CJS support and uncouples the directive from the install method

### PR DESCRIPTION
**Pull request by OmgImAlexis**
If there's anything I need to change please just let me know.

### CODE REVIEW

**Comment by jofftiquez** [comment]
Hi @OmgImAlexis thanks for the PR, really appreciated. May I know what exactly are the scopes/goals of this PR? Thank you :)

**Comment by OmgImAlexis** [comment]
The main two are the get `ESM/CJS` support properly added and splitting the component out so it can be included by itself.

The ESM/CJS stuff allows people using `webpack`, etc. to import modules instead of using the compiled file from babel. This means `tree-shaking`, etc. all works now.

Splitting the directive out of the install method allows using this like so which I prefer as it means I'm not polluting the global component registry.

```vue
<template>
  <img src="foo.png" v-img-fallback="imgFallback">
</template>

<script>
import { ImgFallback } from 'v-img-fallback';

export default {
  components: {
    ImgFallback
  },
  data: () => {
    imgFallback: {
      loading: 'path/to/loading/image',
      error: 'path/to/error/image'
    }
  }
};
</script>
```

**Comment by jofftiquez** [comment]
Great! @OmgImAlexis Thanks. Will publish this soon.

**Comment by OmgImAlexis** [comment]
@jofftiquez thank you so much. If you find any issues related to these changes anywhere into the future at all please don't hesitate to tag me and I'll be sure to help fix the issue. 😄

**Comment by jofftiquez** [comment]
@OmgImAlexis I sure will. I still got more plugins that need PR tho, you might wanna check them out too 😝 Thanks again!

**Pull request merged**
